### ISSUE TITLE
Enable Link-Time Optimization (LTO) once again

### ISSUE THREAD

**Issue by zamazan4ik** [optiprism-io/optiprism#290]
Hi!

I noticed that in the `Cargo.toml` file Link-Time Optimization (LTO) for the project is not enabled. I suggest switching it on since it will reduce the binary size (always a good thing to have) and will likely improve the application's performance a bit since it allows the compiler to perform optimizations in a better way. I see that LTO was disabled in [this](https://github.com/optiprism-io/optiprism/commit/4eb08bdb0b247fe344653fea45fb590116e6b6b7) commit but didn't find reasons in the git commit history. Probably we can revisit this decision and enable it back (probably not the "Fat" version - there are other options nowadays).

I suggest enabling LTO only for the Release builds so as not to sacrifice the developers' experience while working on the project since LTO consumes an additional amount of time to finish the compilation routine. If you think that a regular Release build should not be affected by such a change as well, then I suggest adding an additional `dist` or `release-lto` profile where additionally to regular `release` optimizations LTO will also be added. Such a change simplifies life for maintainers and others interested in the project persons who want to build the most performant version of the application. Using ThinLTO should also help to reduce the build-time overhead with LTO. If we enable it on the Cargo profile level, users, who install the application with `cargo install`, will get the LTO-optimized version "automatically". E.g., check `cargo-outdated` Release [profile](https://github.com/kbknapp/cargo-outdated/blob/master/Cargo.toml#L48).

Thank you.

P.S. It's more like an improvement idea rather than a bug. I created the issue just because the Discussions are disabled for the repo for now.

**Comment by ravlio** [comment]
Hi! 
You're right, I disabled LTO because it is slow to compile. But on the other hand — we can add a `release-lto` profile as you proposed. At the same time, I benchmarked LTO-optimized and I can't say it faster, maybe in some way.

I enabled discussions by the way.

**Comment by zamazan4ik** [comment]
Yeah, `release-lto` could be a good option for the project.

> I benchmarked..

By the way, what benchmarks did you use for that? The "default" one that is available via `cargo bench`? I guess they could be helpful for my another proposal: https://github.com/optiprism-io/optiprism/discussions/292

**Comment by ravlio** [comment]
Unfortunately, I didn't have time to make meaningful benchmarks. There are several ones, but they are outdated. I benchmark the system by hand against running instance. The spread is big — it can vary from 1ms to 10ms. Because the storage part is io-bound and the performance of IO is unpredictable. I'll try to isolate it and benchmark crucial parts. Maybe because of this, I couldn't detect any significant improvements with LTO.
